language: java

before_install:
  - chmod +x gradlew

install: skip

os: linux
dist: trusty
jdk: adopt-openj9@1.11.0-4
#matrix:
#  - TRAVIS_JDK=adopt-openj9@1.11.0-4

#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build --scan -s --refresh-dependencies

after_success:
  - bash <(curl -s https://codecov.io/bash)