language: java

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 11.0.12-open
  - sdk use java 11.0.12-open
  - chmod +x gradlew

install: skip

os: linux
dist: trusty

script:
  - ./gradlew build --refresh-dependencies

after_success:
  - bash <(curl -s https://codecov.io/bash)